spring:
  application:
    name: demo
  data:
    mongodb:
      database: metrics
      host: localhost
      port: 27017
      username: mongo
      password: mongo
      authentication-database: admin